apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  selector:
    app: apache
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200