kind: Service                             
apiVersion: v1
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: myweb                    
  type: LoadBalancer  